# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qkd.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tqkd.proto\x12\x03qkd\";\n\x12OpenConnectRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x12\n\nauth_token\x18\x02 \x01(\t\"N\n\x13OpenConnectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rsession_token\x18\x03 \x01(\t\"6\n\rGetKeyRequest\x12\x0e\n\x06key_id\x18\x01 \x01(\t\x12\x15\n\rsession_token\x18\x02 \x01(\t\"[\n\x0eGetKeyResponse\x12\x10\n\x08key_data\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x15\n\rsession_token\x18\x04 \x01(\t\"8\n\x0c\x43loseRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x15\n\rsession_token\x18\x02 \x01(\t\"1\n\rCloseResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xbe\x01\n\x17QKDKeyManagementService\x12@\n\x0bOpenConnect\x12\x17.qkd.OpenConnectRequest\x1a\x18.qkd.OpenConnectResponse\x12\x31\n\x06GetKey\x12\x12.qkd.GetKeyRequest\x1a\x13.qkd.GetKeyResponse\x12.\n\x05\x43lose\x12\x11.qkd.CloseRequest\x1a\x12.qkd.CloseResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qkd_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OPENCONNECTREQUEST']._serialized_start=18
  _globals['_OPENCONNECTREQUEST']._serialized_end=77
  _globals['_OPENCONNECTRESPONSE']._serialized_start=79
  _globals['_OPENCONNECTRESPONSE']._serialized_end=157
  _globals['_GETKEYREQUEST']._serialized_start=159
  _globals['_GETKEYREQUEST']._serialized_end=213
  _globals['_GETKEYRESPONSE']._serialized_start=215
  _globals['_GETKEYRESPONSE']._serialized_end=306
  _globals['_CLOSEREQUEST']._serialized_start=308
  _globals['_CLOSEREQUEST']._serialized_end=364
  _globals['_CLOSERESPONSE']._serialized_start=366
  _globals['_CLOSERESPONSE']._serialized_end=415
  _globals['_QKDKEYMANAGEMENTSERVICE']._serialized_start=418
  _globals['_QKDKEYMANAGEMENTSERVICE']._serialized_end=608
# @@protoc_insertion_point(module_scope)
