# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import qkd_pb2 as qkd__pb2


class QKDKeyManagementServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenConnect = channel.unary_unary(
                '/qkd.QKDKeyManagementService/OpenConnect',
                request_serializer=qkd__pb2.OpenConnectRequest.SerializeToString,
                response_deserializer=qkd__pb2.OpenConnectResponse.FromString,
                )
        self.GetKey = channel.unary_unary(
                '/qkd.QKDKeyManagementService/GetKey',
                request_serializer=qkd__pb2.GetKeyRequest.SerializeToString,
                response_deserializer=qkd__pb2.GetKeyResponse.FromString,
                )
        self.Close = channel.unary_unary(
                '/qkd.QKDKeyManagementService/Close',
                request_serializer=qkd__pb2.CloseRequest.SerializeToString,
                response_deserializer=qkd__pb2.CloseResponse.FromString,
                )


class QKDKeyManagementServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OpenConnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QKDKeyManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenConnect': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenConnect,
                    request_deserializer=qkd__pb2.OpenConnectRequest.FromString,
                    response_serializer=qkd__pb2.OpenConnectResponse.SerializeToString,
            ),
            'GetKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKey,
                    request_deserializer=qkd__pb2.GetKeyRequest.FromString,
                    response_serializer=qkd__pb2.GetKeyResponse.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=qkd__pb2.CloseRequest.FromString,
                    response_serializer=qkd__pb2.CloseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qkd.QKDKeyManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QKDKeyManagementService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OpenConnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qkd.QKDKeyManagementService/OpenConnect',
            qkd__pb2.OpenConnectRequest.SerializeToString,
            qkd__pb2.OpenConnectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qkd.QKDKeyManagementService/GetKey',
            qkd__pb2.GetKeyRequest.SerializeToString,
            qkd__pb2.GetKeyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qkd.QKDKeyManagementService/Close',
            qkd__pb2.CloseRequest.SerializeToString,
            qkd__pb2.CloseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
